"""
Django settings for sobrietyproj project.

Generated by 'django-admin startproject' using Django 2.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'ja%-)!-drx5w)4b!5r&9*p=d06j%%u6#to(x1w3*4vjvftec=w'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# SECURE_SSL_REDIRECT = True


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'sobriety.apps.SobrietyConfig',
    'fcm_django',
]

FCM_DJANGO_SETTINGS = {
        "FCM_SERVER_KEY": "AIzaSyCv-E9vrhNmuEQ3-tm6H2YYOuS7JW4RCVY"
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'sobrietyproj.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        # 'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            'loaders': [
                'django.template.loaders.filesystem.Loader',
                'django.template.loaders.app_directories.Loader'
            ],
        },
    },
]

WSGI_APPLICATION = 'sobrietyproj.wsgi.application'
DATA_UPLOAD_MAX_MEMORY_SIZE = 115242880


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',

        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
         },

        'NAME': 'SobrietyNetwork$sobriety',
        'USER': 'SobrietyNetwork',
        'PASSWORD': '!@#$%qwe12345',
        'HOST': 'SobrietyNetwork.mysql.pythonanywhere-services.com'
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

URL = 'https://www.thesobrietynetwork.com'

TEXTLOCAL_USERNAME = 'thesobrietynetworkapp@gmail.com'     #  https://control.txtlocal.co.uk/
TEXTLOCAL_PASSWORD = 'Sobriety2018'

STRIPE_LIVE_SECRET_KEY = 'sk_live_FxD6EzNGCUrAL07XlN2V8shp'       #   sk_live_FxD6EzNGCUrAL07XlN2V8shp
STRIPE_TEST_SECRET_KEY = 'sk_test_fnEgPUnGMKefbiox98QzoAzi'       #   sk_test_fnEgPUnGMKefbiox98QzoAzi              sk_test_HotAv9pKJGRL7sY75zWeZRFr

ADMIN_PHONENUMBER = '13175184250'
ADMIN_CODE = '717696'
ADMIN_EMAIL = 'ChemkoTech@yahoo.com'
ADMIN_FIRST_NAME = 'Mitch'
ADMIN_LAST_NAME = 'Coco'

TWILIO_ACCOUNT_SID = 'AC689ad45303ac14ba5776dd21baf6e040'
TWILIO_AUTH_TOKEN = 'a1896034e922287573984d2978e94679'
TWILIO_PHONE_NUMBER = '+19543888593'
PLAY_STORE_APP_URL = 'https://play.google.com/store/apps/details?id=com.sobriety.sobriety'
APPLE_STORE_APP_URL = 'https://itunes.apple.com/us/app/the-sobriety-network/id1444969352?ls=1&mt=8'














